parameters:
    my_user_provider.class:  UserBundle\Security\Core\User\FOSUBUserProvider
    
services:
    tracker_user.registration.form.type:
        class: UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: tracker_user_registration }
            
    tracker_user.profile.form.type:
        class: UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: tracker_user_profile }            
            
    tracker_user.login_listener:
        class: UserBundle\Core\Listener\InteractiveLogin
        arguments: ["@service_container", "@doctrine.orm.entity_manager", "@fos_user.user_manager"]
        tags:
          - { name: kernel.event_listener, event: security.interactive_login, method: onLogin }
          - { name: kernel.event_listener, event: fos_user.registration.confirmed, method: onConfirmed }
          - { name: kernel.event_listener, event: fos_user.resetting.reset.completed, method: onConfirmed }
          
    tracker_user.logout_success_handler:
        class:  UserBundle\Core\Listener\LogoutSuccessHandler
        #arguments:  [@service_container, @router]          
        arguments:  ["@router", "@fos_user.user_manager", "@security.context"]  
        
    my_user_provider:
        class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager,{facebook: facebook_id, google: google_id}]
        #arguments: [@fos_user.user_manager,{facebook: facebook_id, google: google_id, linkedin: linkedin_id}]